# version: "3.9"

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    restart: unless-stopped
    user: root
    env_file:
      - .env
    environment:
      - JENKINS_HOME=/var/jenkins_home
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.casc.yml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins.casc.yml:/var/jenkins_home/casc_configs/jenkins.casc.yml
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    driver: local