jenkins:
  systemMessage: "🚀 Jenkins configured as code - Automated CI/CD"
  numExecutors: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "http://localhost:8080/"

  

jobs:
  - script: >
      pipelineJob('git-documentation-pipeline') {
        description('CI/CD pipeline for git-documentation project')
        parameters {
          choiceParam('ENVIRONMENT', ['dev', 'qa', 'staging', 'prod'], 'Select environment')
          stringParam('GIT_BRANCH', 'main', 'Git branch to build')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote('https://github.com/mudunuri010/git-documentation')
                branch('*/main')
                extensions { cleanBeforeCheckout() }
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
